eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,
                   http://localhost:8762/eureka/
  instance:
    hostname: localhost
server:
  port: 8888
spring:
  application:
    name: STOCK-SERVICE