eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/,
        http://localhost:8761/eureka/

  instance:
    hostname: localhost



server:
  port: 4040
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/stock/**